# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, inputs, defaults, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
      inputs.self.nixosModules.overlays
    ];

  # Enable flakes feature
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  environment.systemPackages = with pkgs; [
    helix
    git
    fish
    wget
    nixfmt
  ];

  # Workaround for vscode-remote-server
  programs.nix-ld.enable = true;


  users.users.luyan = {
    uid = 501;
    extraGroups = [ "wheel" "orbstack" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/luyan";
    homeMode = "700";
    useDefaultShell = true;
  };

  # Integrate home-manager as a NixOS module
  home-manager.users.luyan.imports = [ ../../home-manager/luyan-orb.nix ];

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Shanghai";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
    # orbstack.nix manages /etc/resolv.conf directly
    resolvconf.enable = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIICDDCCAbKgAwIBAgIQPEmFKE/eRgcFHrSLc2AUyzAKBggqhkjOPQQDAjBmMR0w
GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
IENBMB4XDTI1MDkxNjEzNDc0MFoXDTM1MDkxNjEzNDc0MFowZjEdMBsGA1UEChMU
T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABJV7bafoPXiU2UUOXmNILOOkBKikMQyFkEqe
y+uKEyXE6lWb6iepNSD7rsK9TFmPHZl8ctPzqeSVJXyLxlBUnq2jQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR2kF+0wgQCniak
vHo/NodveLtNczAKBggqhkjOPQQDAgNIADBFAiEA6fGabPSBU0Vrwe41hMRICr28
N2RLdavZlTUrOgWUaa0CIHNTl/lpSIkTvG4n+B5tWXuSgEN6SpQqJu1q1fGjBZE5
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIICDDCCAbKgAwIBAgIQPEmFKE/eRgcFHrSLc2AUyzAKBggqhkjOPQQDAjBmMR0w
GwYDVQQKExRPcmJTdGFjayBEZXZlbG9wbWVudDEeMBwGA1UECwwVQ29udGFpbmVy
cyAmIFNlcnZpY2VzMSUwIwYDVQQDExxPcmJTdGFjayBEZXZlbG9wbWVudCBSb290
IENBMB4XDTI1MDkxNjEzNDc0MFoXDTM1MDkxNjEzNDc0MFowZjEdMBsGA1UEChMU
T3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5lcnMgJiBTZXJ2
aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9vdCBDQTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABJV7bafoPXiU2UUOXmNILOOkBKikMQyFkEqe
y+uKEyXE6lWb6iepNSD7rsK9TFmPHZl8ctPzqeSVJXyLxlBUnq2jQjBAMA4GA1Ud
DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR2kF+0wgQCniak
vHo/NodveLtNczAKBggqhkjOPQQDAgNIADBFAiEA6fGabPSBU0Vrwe41hMRICr28
N2RLdavZlTUrOgWUaa0CIHNTl/lpSIkTvG4n+B5tWXuSgEN6SpQqJu1q1fGjBZE5
-----END CERTIFICATE-----

    ''
  ];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "26.05"; # Did you read the comment?
}
